### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by MrConqueror** [DawntDev/MangaReader-App#2] opened 2023-09-27 04:52 UTC
the app doesn't open it closes itself please update

**Comment by DawntDev** [comment] 2023-09-27 11:25
@MrConqueror Hello, if this is because the service where the Backend was deployed has already been closed. If you wish, I can share the Backend repository with you, and you can make your own deployment.

**Comment by DawntDev** [comment] 2023-09-27 11:40
Or the other, I ask you to wait for me while I find a service through which I can deploy the Backend.

**Comment by DawntDev** [comment] 2023-09-27 11:41
I promise to spend time on it this week.

**Comment by DawntDev** [comment] 2024-07-21 22:03
The issue is resolved in the last commit

**Closed as completed by DawntDev** 2024-07-21 22:03 UTC
Labels: bug
